apiVersion: v1
kind: ConfigMap
metadata:
  name: flarum-default-configmap
  namespace: default
data:
  DB_USER: "{{.Values.appProperties.database.user}}"
  DB_PASSWORD: "{{.Values.appProperties.database.password}}"
  DB_HOST: "{{.Values.appProperties.database.host}}"
  DB_NAME: "{{.Values.appProperties.database.name}}"
  DB_PORT: "{{.Values.appProperties.database.port}}"
  FLARUM_BASE_URL: "{{.Values.appProperties.baseUrl}}"